version: '3'
services:
  # Laravel Application
  app:
    image: php:7.4-fpm
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./laravel:/var/www
    networks:
      - laravel-net
    restart: unless-stopped

  # Nginx Web Server


  web:
    build: 
      context: ./web
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"   #8001 of the host to 3000 if the container
    container_name: nginx-server
    depends_on:
      - app
    networks:
      - laravel-net
    restart: unless-stopped
    volumes:
      - ./laravel/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf


 

  # MySQL Database
  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - laravel-net
    restart: unless-stopped

networks:
  laravel-net:
