version: '3'
services:
  app:
    build:
      context: ./laravel-app
      dockerfile: Dockerfile.laravel
    container_name: laravel-app
    working_dir: /var/www
    volumes:
      - ./laravel-app:/var/www
    networks:
      - laravel-net
    restart: unless-stopped

  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./laravel-app/public:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel-net
    restart: unless-stopped

  db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
    networks:
      - laravel-net
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: laravel_user
      PMA_PASSWORD: laravel_password
    ports:
      - "8080:80"
    networks:
      - laravel-net
    restart: unless-stopped

networks:
  laravel-net:
