# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy your custom Nginx configuration into the container
#COPY ./nginx-config/my-nginx-config.conf /etc/nginx/conf.d/default.conf

# Expose the necessary ports if needed
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]
